"""Fix cascade deletes for course relationships

Revision ID: 236bd9a58464
Revises: 5308aae7ca4c
Create Date: 2025-11-17 14:36:59.508200

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '236bd9a58464'
down_revision: Union[str, Sequence[str], None] = '5308aae7ca4c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('content_items_external_link_id_fkey'), 'content_items', type_='foreignkey')
    op.drop_constraint(op.f('content_items_video_id_fkey'), 'content_items', type_='foreignkey')
    op.drop_constraint(op.f('content_items_document_id_fkey'), 'content_items', type_='foreignkey')
    op.create_foreign_key(None, 'content_items', 'documents', ['document_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'content_items', 'external_links', ['external_link_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'content_items', 'videos', ['video_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'content_items', type_='foreignkey')
    op.drop_constraint(None, 'content_items', type_='foreignkey')
    op.drop_constraint(None, 'content_items', type_='foreignkey')
    op.create_foreign_key(op.f('content_items_document_id_fkey'), 'content_items', 'documents', ['document_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(op.f('content_items_video_id_fkey'), 'content_items', 'videos', ['video_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(op.f('content_items_external_link_id_fkey'), 'content_items', 'external_links', ['external_link_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###
