"""addded json

Revision ID: 5308aae7ca4c
Revises: 5b34c59ac978
Create Date: 2025-11-08 20:58:41.780358

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5308aae7ca4c'
down_revision: Union[str, Sequence[str], None] = '5b34c59ac978'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('main_topics', sa.JSON(), server_default='{}', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('documents', 'main_topics')
    # ### end Alembic commands ###
