"""author_id set null in announcment

Revision ID: 5b34c59ac978
Revises: 9aac916e009b
Create Date: 2025-10-29 22:28:43.079996

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5b34c59ac978'
down_revision: Union[str, Sequence[str], None] = '9aac916e009b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_progress')
    op.alter_column('announcements', 'author_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint(op.f('announcements_author_id_fkey'), 'announcements', type_='foreignkey')
    op.create_foreign_key(None, 'announcements', 'users', ['author_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'announcements', type_='foreignkey')
    op.create_foreign_key(op.f('announcements_author_id_fkey'), 'announcements', 'users', ['author_id'], ['id'], ondelete='CASCADE')
    op.alter_column('announcements', 'author_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.create_table('user_progress',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('content_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('progress', sa.DOUBLE_PRECISION(precision=53), server_default=sa.text("'0'::double precision"), autoincrement=False, nullable=False),
    sa.Column('completed_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('last_viewed_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['content_id'], ['content_items.id'], name=op.f('user_progress_content_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('user_progress_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('user_progress_pkey')),
    sa.UniqueConstraint('user_id', 'content_id', name=op.f('uq_user_content'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    # ### end Alembic commands ###
