"""add_prerequisite_content_ids_to_course_quizzes

Revision ID: 5fdc92addd8b
Revises: e9fd3fa98732
Create Date: 2026-01-25 18:43:17.442597

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5fdc92addd8b'
down_revision: Union[str, Sequence[str], None] = 'e9fd3fa98732'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Add prerequisite_content_ids column with default empty array."""
    # Add column with default empty array for existing quizzes
    op.add_column('course_quizzes', sa.Column('prerequisite_content_ids', sa.JSON(), nullable=False, server_default='[]'))
    
    # Remove server default after setting initial values
    op.alter_column('course_quizzes', 'prerequisite_content_ids', server_default=None)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('course_quizzes', 'prerequisite_content_ids')
    # ### end Alembic commands ###
