"""init schema

Revision ID: 6a142cc7bc7c
Revises: 
Create Date: 2025-10-21 23:00:26.754471

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6a142cc7bc7c'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_progress')
    op.add_column('courses', sa.Column('thumbnail_public_id', sa.String(), nullable=True))
    op.create_index(op.f('ix_document_processing_audit_document_id'), 'document_processing_audit', ['document_id'], unique=False)
    op.create_index(op.f('ix_document_processing_audit_job_id'), 'document_processing_audit', ['job_id'], unique=False)
    op.create_index(op.f('ix_document_processing_audit_status'), 'document_processing_audit', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_document_processing_audit_status'), table_name='document_processing_audit')
    op.drop_index(op.f('ix_document_processing_audit_job_id'), table_name='document_processing_audit')
    op.drop_index(op.f('ix_document_processing_audit_document_id'), table_name='document_processing_audit')
    op.drop_column('courses', 'thumbnail_public_id')
    op.create_table('user_progress',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('content_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('progress', sa.DOUBLE_PRECISION(precision=53), server_default=sa.text("'0'::double precision"), autoincrement=False, nullable=False),
    sa.Column('completed_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('last_viewed_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['content_id'], ['content_items.id'], name=op.f('user_progress_content_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('user_progress_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('user_progress_pkey')),
    sa.UniqueConstraint('user_id', 'content_id', name=op.f('uq_user_content'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    # ### end Alembic commands ###
