"""deadline weeks

Revision ID: 6b0deb6bfce3
Revises: 5ec68435e9c6
Create Date: 2026-02-08 15:57:24.329190

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6b0deb6bfce3'
down_revision: Union[str, Sequence[str], None] = '5ec68435e9c6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('courses', sa.Column('deadline_weeks', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('courses', 'deadline_weeks')
    # ### end Alembic commands ###
