"""external links

Revision ID: 956cf521d02a
Revises: 89353012aaec
Create Date: 2025-10-25 16:52:35.186034

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '956cf521d02a'
down_revision: Union[str, Sequence[str], None] = '89353012aaec'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_progress')
    op.add_column('content_items', sa.Column('external_link_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'content_items', 'external_links', ['external_link_id'], ['id'], ondelete='SET NULL')
    op.drop_column('content_items', 'external_url')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('content_items', sa.Column('external_url', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'content_items', type_='foreignkey')
    op.drop_column('content_items', 'external_link_id')
    op.create_table('user_progress',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('content_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('progress', sa.DOUBLE_PRECISION(precision=53), server_default=sa.text("'0'::double precision"), autoincrement=False, nullable=False),
    sa.Column('completed_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('last_viewed_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['content_id'], ['content_items.id'], name=op.f('user_progress_content_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('user_progress_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('user_progress_pkey')),
    sa.UniqueConstraint('user_id', 'content_id', name=op.f('uq_user_content'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    # ### end Alembic commands ###
