"""Add related_course_id to announcements

Revision ID: a308d57826bc
Revises: b1707b7bcb25
Create Date: 2026-02-14 23:44:09.755958

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a308d57826bc'
down_revision: Union[str, Sequence[str], None] = 'b1707b7bcb25'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('announcements', sa.Column('related_course_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'announcements', 'courses', ['related_course_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'announcements', type_='foreignkey')
    op.drop_column('announcements', 'related_course_id')
    # ### end Alembic commands ###
