"""add_order_index_to_content_items

Revision ID: e9fd3fa98732
Revises: a5f22726d543
Create Date: 2026-01-25 17:37:50.251008

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e9fd3fa98732'
down_revision: Union[str, Sequence[str], None] = 'a5f22726d543'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Add order_index column and set initial values based on created_at."""
    # Add the column with default value 0
    op.add_column('content_items', sa.Column('order_index', sa.Integer(), nullable=False, server_default='0'))
    
    # Set initial order_index values based on created_at within each course
    op.execute("""
        UPDATE content_items 
        SET order_index = subquery.row_num - 1
        FROM (
            SELECT id, 
                   ROW_NUMBER() OVER (PARTITION BY course_id ORDER BY created_at ASC) as row_num
            FROM content_items
        ) as subquery
        WHERE content_items.id = subquery.id
    """)
    
    # Remove the server default after setting values
    op.alter_column('content_items', 'order_index', server_default=None)
    
    # Create the index
    op.create_index('ix_content_course_order', 'content_items', ['course_id', 'order_index'], unique=False)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_content_course_order', table_name='content_items')
    op.drop_column('content_items', 'order_index')
    # ### end Alembic commands ###
