"""Add Cloudinary fields to documents

Revision ID: ec1651016582
Revises: 9ee0cbfaba9a
Create Date: 2025-10-18 15:26:26.195696

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ec1651016582'
down_revision: Union[str, Sequence[str], None] = '9ee0cbfaba9a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('cloudinary_url', sa.String(), nullable=True))
    op.add_column('documents', sa.Column('cloudinary_public_id', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('documents', 'cloudinary_public_id')
    op.drop_column('documents', 'cloudinary_url')
    # ### end Alembic commands ###
