"""added user profile link

Revision ID: f9e2053b814f
Revises: 1d60b216758b
Create Date: 2025-11-25 21:44:54.439645

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f9e2053b814f'
down_revision: Union[str, Sequence[str], None] = '1d60b216758b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('profile_picture_url', sa.String(), nullable=True))
    op.add_column('users', sa.Column('profile_picture_public_id', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'profile_picture_public_id')
    op.drop_column('users', 'profile_picture_url')
    # ### end Alembic commands ###
