"""link_quiz_directly_to_course

Revision ID: fa3a9ce687c9
Revises: 06f458d7e7a1
Create Date: 2026-01-25 15:47:59.993352

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fa3a9ce687c9'
down_revision: Union[str, Sequence[str], None] = '06f458d7e7a1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('content_items_quiz_id_fkey'), 'content_items', type_='foreignkey')
    op.drop_column('content_items', 'quiz_id')
    op.add_column('course_quizzes', sa.Column('course_id', sa.Integer(), nullable=False))
    op.create_index('ix_course_quiz_course', 'course_quizzes', ['course_id'], unique=False)
    op.create_index(op.f('ix_course_quizzes_course_id'), 'course_quizzes', ['course_id'], unique=False)
    op.create_foreign_key(None, 'course_quizzes', 'courses', ['course_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'course_quizzes', type_='foreignkey')
    op.drop_index(op.f('ix_course_quizzes_course_id'), table_name='course_quizzes')
    op.drop_index('ix_course_quiz_course', table_name='course_quizzes')
    op.drop_column('course_quizzes', 'course_id')
    op.add_column('content_items', sa.Column('quiz_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('content_items_quiz_id_fkey'), 'content_items', 'course_quizzes', ['quiz_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###
